version: "2"

services:
    openldap:
        image: osixia/openldap:1.2.1
        container_name: openldap
        environment:
            LDAP_ORGANISATION: Curso
            LDAP_DOMAIN: curso.com
            LDAP_ADMIN_PASSWORD: password
            LDAP_TLS: "false"
            LDAP_TLS_ENFORCE: "false"
            LDAP_TLS_VERIFY_CLIENT: "never"
        tty: true
        stdin_open: true
        command: --copy-service
        volumes:
          - ./ldap:/container/service/slapd/assets/config/bootstrap/ldif/custom:rw
        domainname: "curso.com" 
        hostname: "ldap.curso.com"
        ports:
            - 389:389

    phpldapadmin:
        image: osixia/phpldapadmin:latest
        container_name: phpldapadmin
        environment:
          PHPLDAPADMIN_LDAP_HOSTS: "openldap"
          PHPLDAPADMIN_HTTPS: "false"
        ports:
          - "8081:80"
        depends_on:
          - openldap

