version: "2"

services:

    openldap:
        image: osixia/openldap:latest
        command: "--loglevel info"
        container_name: ldapserver
        hostname: ldapserver
        ports:
          - "389:389" # Comunicación no securizada ldap://
          - "636:636" # Comunicación securizada    ldaps://
        volumes:
          - /home/ubuntu/environment/datos/ldap:/var/lib/ldap
          - /home/ubuntu/environment/datos/slapd/config:/etc/ldap/slapd.d
          - /home/ubuntu/environment/datos/certificates:/container/service/slapd/assets/certs
          - /home/ubuntu/environment/datos/ldifs:/openldap/ldif  
        environment:
          - LDAP_ORGANISATION=curso
          - LDAP_DOMAIN=curso.local
          - LDAP_ADMIN_USERNAME=admin
          - LDAP_ADMIN_PASSWORD=password
          - LDAP_CONFIG_PASSWORD=password
          - "LDAP_BASE_DN=dc=curso,dc=local"
          - LDAP_READONLY_USER=true
          - LDAP_READONLY_USER_USERNAME=user
          - LDAP_READONLY_USER_PASSWORD=password
          - LDAP_SEED_INTERNAL_LDIF_PATH=/openldap/ldif
            # Usuario del ldap.   dn -> dc=curso,dc=local,cn=admin
    phpldapadmin:
        image: osixia/phpldapadmin:latest
        container_name: phpldapadmin
        hostname: phpldapadmin
        ports:
          - "8084:80"
        environment:
          - PHPLDAPADMIN_LDAP_HOSTS=ldapserver
          - PHPLDAPADMIN_HTTPS=false
        depends_on:
          - openldap